USE STRESS_CHECK;

CREATE TABLE EMPLOYEE (
	EMP_ID CHAR(5) PRIMARY KEY,
	EMP_NAME NVARCHAR(20) NOT NULL,
	GENDER CHAR(1) NOT NULL,
	CONSTRAINT GENDER_CHK CHECK(GENDER IN ('M','F'))
);

CREATE TABLE QUESTION (
	Q_CATEGORY CHAR(1) NOT NULL,
	Q_NO INT NOT NULL,
	TYPE INT NOT NULL,
	REV BIT NOT NULL,
	FACTOR INT NOT NULL,
	REV_2 BIT NOT NULL,
	Q_TEXT NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Q_CATEGORY, Q_NO)
);

CREATE TABLE QUESTION_TITLE (
	Q_CATEGORY CHAR(1) PRIMARY KEY,
	TITLE NVARCHAR(100) NOT NULL,
	ANSWER_1 VARCHAR(30) NOT NULL,
	ANSWER_2 VARCHAR(30) NOT NULL,
	ANSWER_3 VARCHAR(30) NOT NULL,
	ANSWER_4 VARCHAR(30) NOT NULL
);

CREATE TABLE QUESTION_SUBTITLE (
	Q_CATEGORY CHAR(1) NOT NULL,
	Q_NO INT NOT NULL,
	SUBTITLE NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Q_CATEGORY, Q_NO)
);

CREATE TABLE ANSWER (
	YEAR CHAR(4) NOT NULL,
	EMP_ID CHAR(5) NOT NULL,
	Q_CATEGORY CHAR(1) NOT NULL,
	Q_NO INT NOT NULL,
	ANSWER INT NOT NULL,
	MOD_ANSWER INT NOT NULL,
	MOD_ANSWER_2 INT NOT NULL,
	PRIMARY KEY (YEAR, EMP_ID, Q_CATEGORY, Q_NO),
	--FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (EMP_ID),
	--FOREIGN KEY (Q_CATEGORY, Q_NO) REFERENCES QUESTION (Q_CATEGORY, Q_NO)
);

CREATE TABLE TYPE (
	TYPE INT PRIMARY KEY,
	TYPE_TEXT NVARCHAR(20) NOT NULL,
);

CREATE TABLE FACTOR (
	FACTOR INT PRIMARY KEY,
	REV BIT NOT NULL,
	FACTOR_TEXT NVARCHAR(20) NOT NULL,
);

CREATE TABLE YEAR (
	YEAR CHAR(4) PRIMARY KEY,
	THIS_YEAR BIT NOT NULL
);

CREATE TABLE RESULT_CAT (
	YEAR CHAR(4) NOT NULL,
	EMP_ID CHAR(5) NOT NULL,
	CATEGORY CHAR(1) NOT NULL,
	RESULT INT NOT NULL,
	PRIMARY KEY (YEAR, EMP_ID, CATEGORY)
);

CREATE TABLE RESULT_TYPE (
	YEAR CHAR(4) NOT NULL,
	EMP_ID CHAR(5) NOT NULL,
	TYPE INT NOT NULL,
	RESULT INT NOT NULL,
	PRIMARY KEY (YEAR, EMP_ID, TYPE)
);

CREATE TABLE RESULT_FACTOR (
	YEAR CHAR(4) NOT NULL,
	EMP_ID CHAR(5) NOT NULL,
	FACTOR INT NOT NULL,
	RESULT INT NOT NULL,
	PRIMARY KEY (YEAR, EMP_ID, FACTOR)
);

CREATE TABLE LOGIN (
	EMP_ID CHAR(5) PRIMARY KEY,
	PASSWD VARCHAR(MAX)
);