DECLARE @YEAR INT = 2024;
DECLARE @EMP_ID CHAR(5) = '10001';
DECLARE @Q_CATEGORY CHAR(1) = 'A';
DECLARE @Q_NO INT = 1;

SELECT T.TITLE, T.Q_CATEGORY, Q.Q_NO, Q.Q_TEXT, T.ANSWER_1, T.ANSWER_2, T.ANSWER_3, T.ANSWER_4, Q.REV, S.SUBTITLE
FROM QUESTION_TITLE AS T
LEFT JOIN QUESTION AS Q ON T.Q_CATEGORY = Q.Q_CATEGORY
LEFT JOIN QUESTION_SUBTITLE AS S ON Q.Q_CATEGORY = S.Q_CATEGORY AND Q.Q_NO = S.Q_NO
WHERE T.Q_CATEGORY = @Q_CATEGORY;

SELECT A.YEAR, A.EMP_ID, A.Q_CATEGORY, A.Q_NO, A.ANSWER, A.MOD_ANSWER, A.MOD_ANSWER_2, Q.TYPE, Q.FACTOR, Q.REV, Q.REV_2
FROM ANSWER A
LEFT JOIN QUESTION Q ON A.Q_CATEGORY = Q.Q_CATEGORY AND A.Q_NO = Q.Q_NO
WHERE YEAR = @YEAR AND EMP_ID = @EMP_ID;

WITH CategorySums AS (
	SELECT
		SUM(CASE WHEN A.Q_CATEGORY = 'A' THEN A.MOD_ANSWER ELSE 0 END) AS sum_A,
		SUM(CASE WHEN A.Q_CATEGORY = 'B' THEN A.MOD_ANSWER ELSE 0 END) AS sum_B,
		SUM(CASE WHEN A.Q_CATEGORY = 'C' THEN A.MOD_ANSWER ELSE 0 END) AS sum_C,
		SUM(CASE WHEN A.Q_CATEGORY = 'D' THEN A.MOD_ANSWER ELSE 0 END) AS sum_D
	FROM ANSWER A
	LEFT JOIN QUESTION Q ON A.Q_CATEGORY = Q.Q_CATEGORY AND A.Q_NO = Q.Q_NO
	WHERE YEAR = @YEAR AND EMP_ID = @EMP_ID
)
SELECT
	CASE
		WHEN (sum_A + sum_C > 76 AND sum_B > 63) OR sum_B > 77 THEN 'High'
		ELSE 'Normal'
	END AS stress_level
FROM CategorySums;

